services:
  postgres:
    image: postgres:latest
    container_name: secondhand-postgres

    environment:
      POSTGRES_USER: secondhand_user
      POSTGRES_PASSWORD: secondhand_password
      POSTGRES_DB: secondhand_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

volumes:
  postgres_data: